remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-minimal
title: Support page of my products
description: Site, where you can contact me and look at my projects
logo: /assets/A.png
